# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Coffee1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, coffee_name: str=None):  # noqa: E501
        """Coffee1 - a model defined in Swagger

        :param coffee_name: The coffee_name of this Coffee1.  # noqa: E501
        :type coffee_name: str
        """
        self.swagger_types = {
            'coffee_name': str
        }

        self.attribute_map = {
            'coffee_name': 'coffee_name'
        }

        self._coffee_name = coffee_name

    @classmethod
    def from_dict(cls, dikt) -> 'Coffee1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The coffee_1 of this Coffee1.  # noqa: E501
        :rtype: Coffee1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def coffee_name(self) -> str:
        """Gets the coffee_name of this Coffee1.


        :return: The coffee_name of this Coffee1.
        :rtype: str
        """
        return self._coffee_name

    @coffee_name.setter
    def coffee_name(self, coffee_name: str):
        """Sets the coffee_name of this Coffee1.


        :param coffee_name: The coffee_name of this Coffee1.
        :type coffee_name: str
        """

        self._coffee_name = coffee_name
