# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, coffee_name: str=None, milk: str=None, timestamp: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param coffee_name: The coffee_name of this InlineResponse200.  # noqa: E501
        :type coffee_name: str
        :param milk: The milk of this InlineResponse200.  # noqa: E501
        :type milk: str
        :param timestamp: The timestamp of this InlineResponse200.  # noqa: E501
        :type timestamp: str
        """
        self.swagger_types = {
            'coffee_name': str,
            'milk': str,
            'timestamp': str
        }

        self.attribute_map = {
            'coffee_name': 'coffee_name',
            'milk': 'milk',
            'timestamp': 'timestamp'
        }

        self._coffee_name = coffee_name
        self._milk = milk
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def coffee_name(self) -> str:
        """Gets the coffee_name of this InlineResponse200.


        :return: The coffee_name of this InlineResponse200.
        :rtype: str
        """
        return self._coffee_name

    @coffee_name.setter
    def coffee_name(self, coffee_name: str):
        """Sets the coffee_name of this InlineResponse200.


        :param coffee_name: The coffee_name of this InlineResponse200.
        :type coffee_name: str
        """

        self._coffee_name = coffee_name

    @property
    def milk(self) -> str:
        """Gets the milk of this InlineResponse200.


        :return: The milk of this InlineResponse200.
        :rtype: str
        """
        return self._milk

    @milk.setter
    def milk(self, milk: str):
        """Sets the milk of this InlineResponse200.


        :param milk: The milk of this InlineResponse200.
        :type milk: str
        """

        self._milk = milk

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this InlineResponse200.


        :return: The timestamp of this InlineResponse200.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this InlineResponse200.


        :param timestamp: The timestamp of this InlineResponse200.
        :type timestamp: str
        """

        self._timestamp = timestamp
